---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - augur-deployment.yaml
  - augur-svc.yaml
  - config-pvc.yaml
  - facade-pvc.yaml

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/component: backend
      app.kubernetes.io/name: augur-backend
