---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - augurdb-postgrescluster.yaml

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/component: database
      app.kubernetes.io/name: postgres
