# Example Kubernetes Secret for Augur configuration
# Set the usernames and API keys for GitHub and GitLab below and save this file
# as `augur-secret.yaml`.
---
apiVersion: v1
kind: Secret
metadata:
  name: augur-secret
type: Opaque
stringData:
  AUGUR_GITHUB_USERNAME: GHUserName
  AUGUR_GITHUB_API_KEY: ghp_*****  # pragma: allowlist secret
  AUGUR_GITLAB_USERNAME: GLUserName
  AUGUR_GITLAB_API_KEY: glpat-*****  # pragma: allowlist secret
