---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../bases
  # Secret containing GitHub and GitLab tokens (not checked in)
  # Needs to contain:
  # - AUGUR_GITHUB_USERNAME
  # - AUGUR_GITHUB_API_KEY
  # - AUGUR_GITLAB_USERNAME
  # - AUGUR_GITLAB_API_KEY
  - augur-secret.yaml

# Namespace for deployment
namespace: augur-on-ocp

# Mappings for the augur-specific images used in the deployment
images:
  - name: ghcr.io/chaoss/augur_backend
    newName: johnstrunk/augur-backend
    newTag: latest@sha256:a2eb5a3d6797552cb299ab650acb4abcfb2d3ea5b590dfb0dfd8db8f305406fd
  - name: ghcr.io/chaoss/augur_keyman
    newName: johnstrunk/augur-keyman
    newTag: latest@sha256:85d8546c0cba7ff9780c82c4d57c88445a2657e6b31252c342f5e24ca05671dc
