---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - valkey-configmap.yaml
  - valkey-pdb.yaml
  - valkey-services.yaml
  - valkey-statefulset.yaml

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/component: valkey
      app.kubernetes.io/name: augur-valkey
