---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - augur-db-secret.yaml
  - postgres-deployment.yaml
  - postgres-pvc.yaml
  - postgres-svc.yaml

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/component: database
      app.kubernetes.io/name: postgres
