---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
  template:
    spec:
      containers:
        - name: augur-db
          image: postgres:16
          env:
            - name: POSTGRES_DB
              value: "augur"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: augur-db-secret
                  key: AUGUR_DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: augur-db-secret
                  key: AUGUR_DB_PASSWORD
            - name: PGDATA
              value: "/var/lib/postgresql/data/pgdata"
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: augurpostgres
      volumes:
        - name: augurpostgres
          persistentVolumeClaim:
            claimName: postgres
