---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rabbitmq-cluster.yaml
  - rabbitmq-pdb.yaml

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/component: message-queue
      app.kubernetes.io/name: rabbitmq

patches:
  # Force the RabbitMQ Pods to have the common labels so the PDB can select them
  - patch: |-
      apiVersion: rabbitmq.com/v1beta1
      kind: RabbitmqCluster
      metadata:
        name: rabbitmq
      spec:
        override:
          statefulSet:
            spec:
              template:
                metadata:
                  labels:
                    app.kubernetes.io/component: message-queue
                    app.kubernetes.io/name: rabbitmq
