---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
spec:
  serviceName: rabbitmq
  replicas: 1
  template:
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.12-management-alpine
          # Setting node name isn't necessary since the StatefulSet will use
          # predictable names (rabbitmq-0, rabbitmq-1, etc.)
          # env:
          #   - name: RABBITMQ_NODE_NAME
          #     valueFrom:
          #       fieldRef:
          #         fieldPath: metadata.name
          ports:
            - containerPort: 5671   # AMQP 0-9-1 and 1.0 over SSL
            - containerPort: 5672   # AMQP 0-9-1 and 1.0
            - containerPort: 15671  # Management UI over SSL
            - containerPort: 15672  # Management UI
          volumeMounts:
            - name: rabbitmq-data
              mountPath: /var/lib/rabbitmq/mnesia
            - name: rabbitmq-config
              mountPath: /etc/rabbitmq
      volumes:
        - name: rabbitmq-config
          secret:
            secretName: rabbitmq-config  # pragma: allowlist secret
  statefulSetPersistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
    whenScaled: Retain
  volumeClaimTemplates:
    - metadata:
        name: rabbitmq-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
