---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-config
type: Opaque
stringData:
  # https://github.com/rabbitmq/rabbitmq-server/blob/v4.0.x/deps/rabbit/docs/rabbitmq.conf.example
  rabbitmq.conf: |
    default_vhost = augur_vhost
    default_user = augur
    default_pass = password123
    default_permissions.configure = .*
    default_permissions.read = .*
    default_permissions.write = .*
    default_user_tags.administrator = true
    default_user_tags.augur = true
    default_user_tags.augurTag = true
    vm_memory_high_watermark.absolute = 1GB

    # Clustering
    cluster_name = augur.local
    cluster_formation.peer_discovery_backend = classic_config
    cluster_formation.classic_config.nodes.1 = rabbit@rabbitmq-0

    # Max time a consumer can take to ack a message before the connection is
    # force closed
    consumer_timeout = 900000
    log.console = true
    log.file = false
