---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  ports:
    - name: amqp-ssl
      protocol: TCP
      port: 5671
      targetPort: 5671
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: management-ssl
      protocol: TCP
      port: 15671
      targetPort: 15671
    - name: management
      protocol: TCP
      port: 15672
      targetPort: 15672
  type: ClusterIP
