---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - redis-data-pvc.yaml
  - redis-deployment.yaml
  - redis-svc.yaml

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/component: redis
      app.kubernetes.io/name: redis
