---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend
  - flower
  - keyman
  - postgres
  - rabbitmq
  - redis

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: augur
