---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - flower-deployment.yaml
  - flower-svc.yaml

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/component: dashboard
      app.kubernetes.io/name: flower
