---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - keyman-deployment.yaml

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/component: key-manager
      app.kubernetes.io/name: keyman
